#!/bin/bash

echo "We will install some required linux and python programs and packages first."

sudo apt update
sudo apt upgrade
sudo apt install firefox
sudo apt install git
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code
sudo apt-get install dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C99B11DEB97541F0
sudo apt-add-repository https://cli.github.com/packages
sudo apt update
sudo apt install gh
pip3 install -r ./requirements.txt

cp ./bin/{configure.sh,Creatify-GithubCLI.sh,Creatify-WebScraping.sh,creatify,webtemplate.sh,create.py} "/home/mohammadarik/.creatify/"
# cp -r

echo "export PATH=\"\$PATH:/home/mohammadarik/.creatify\"" >> "/home/mohammadarik/.bashrc"
chmod u+x "/home/mohammadarik/.creatify/creatify"\

echo "Please restart the terminal to start using Creatify.."
